### PR TITLE
Get monitor's socket file descriptor from its Builder

### PR DESCRIPTION
**Pull request by losynix**
This allows getting the monitor's socket file descriptor before calling the **listen()** method.
I added a new function but let me know if you prefer implementing the **AsRawFd** trait for the **Builder** struct.

### CODE REVIEW

**Comment by losynix** [comment]
Hello, are you interested in this PR ?

**Comment by Drakulix** [comment]
Hey sorry, this PR kinda slipped through.
What is the use-case of having access to the file descriptor early? It kinda goes against the builder pattern.

**Comment by losynix** [comment]
My use case is tied to [seccomp](https://en.wikipedia.org/wiki/Seccomp), I'd like to enter secure computing mode as soon as possible in my program while still keeping a short list of allowed syscalls.
I don't need/want to allow the `bind` system call on all file descriptors but only on the monitor socket, hence the new function so I can instantiate a `MonitorBuilder`, get its file descriptor, enter seccomp with a filter allowing `bind` (among others) on this fd, then call `listen()` on the monitor builder.

I agree this function seems weird for the builder pattern but I couldn't think of a better way.

**Comment by Drakulix** [comment]
Definitely a good use-case, I would prefer the `AsRawFd`-trait though, if that is not too much to ask for.

**Comment by losynix** [comment]
Sure, I implemented both`AsRawFd` and `AsFd` traits.

**Pull request merged**
