### PR TITLE
lib, device: begin using list::List instead of custom structs

### PR DESCRIPTION
**Pull request by woodruffw**
See #21.

### CODE REVIEW

**Comment by woodruffw** [comment]
(I marked this as draft because I haven't finished porting everything to `list::List` yet.)

**Comment by woodruffw** [comment]
N.B.: This doesn't modify the `enumerator::Devices` implementation, since that uses a custom `Iterator<Item=Device>` rather than `Item=list::Entry`.

**Comment by woodruffw** [comment]
Gentle ping on this :slightly_smiling_face:

**Comment by Drakulix** [comment]
I am wondering, if we could make type aliases for `Property` and `Attribute` to `list::Entry` for backwards compatibility.

But it seems with #23 I need to yank 0.5.1 anyway and it this point we could just do 0.6.0 with `hwdb` and full usage of `list`.



> N.B.: This doesn't modify the `enumerator::Devices` implementation, since that uses a custom `Iterator<Item=Device>` rather than `Item=list::Entry`.

Could we not make `List` generic over the `Entry`-type and make `Entry` the default? (`List<E=Entry<'_>>`)
Then we could re-use `List` for `enumerator::Devices` as well.

**Pull request merged**
