### PR TITLE
Fix "hack" from #14 by using a real `udev` context object

### LINKED ISSUE #18: Enumerating devices on older versions of libudev (eg 215) segfaults
The fix in #13 employs a workaround (the author called it a "hack" so I will do the same, no offence intended) to a segfault that was caused by older versions of `libudev` asserting that the `struct udev*` parameter was non-NULL.  The hack is to pass a bogus non-null pointer to somewhere in the process where an arbitrary empty slice is located.  This apparently works in newer libudev versions because this `struct udev*` parameter is apparently not used for anything.

However, in older versions this is not the case (I don't know when this started, but I can confirm that it's the case in version 215, shipping with Debian 8 "jessie").  As least in 215, libudev assumes this is a valid `struct udev*` created with the `udev_new()` function, and when it's not, the process segfaults.

This hack is dangerous also because it's relying on undocumented behavior that could easily change in the future.  The current [libudev manpage](https://www.man7.org/linux/man-pages//man3/libudev.3.html) explicitly says that functions require a valid `struct udev*` context:

> All functions require a libudev context to operate. This context can
>        be create via udev_new(3). It is used to track library state and link
>        objects together. No global state is used by libudev, everything is
>        always linked to a udev context.

I'll prepare a PR with a safer, more permanent fix for this issue.

### PR DESCRIPTION
**Pull request by anelson**
Summary
---
This introduces an internal (`pub(crate)`) struct `Udev`, which wraps
the libudev `struct udev*` in almost the same way that `Enumerator`
wraps `udev_enumerate*`.  This is then used by `Enumerator::new`,
`Builder::new`, and `Device::from_syspath` to ensure enumerators,
monitors, and devices always have a valid `udev` context.  Any `Device`
instances discovered via `Enumerator` or `Builder` will share the same
`Udev` instance as the `Enumerator` or `Builder` they came from, so the
overhead associated with this change should be minimal.

Tests
---
The existing unit tests did not reproduce this problem when running in
Debian 8 "jessie".  I can't explain why, although I assume that the fact
that the enumerate test limits the results to "hidraw" subsystem may be
a factor.  I added another test to enumerate all devices.

Note that the `list_devices` example program _did_ segfault on Debian
"jessie".

I've also added a test for the new `Udev` struct which exercises the
`clone`/`drop` implementation by making sure the same instance is used
each time.  I ran these tests under `valgrind` to confirm there were no
memory leaks.

Compatibility
---
I've tried to keep the compatibility issues to a minimum, however one
breaking change was unavoidable: `Enumerator`, `Builder`, and `Device`
no longer implement `FromRaw`, because their structs now maintain not
only the `struct udev_enumerate*` but also the Rust `Udev` struct which
contains the context with which that `Enumerator`/`Builder`/`Device` was
created.  This is required to keep the `struct udev*` instance alive for
the duration of other structs' lifetimes.

Ideally the `FromRaw` trait would have been crate-internal anyway, but
since it wasn't before this change I'm not attempting to change its
visibility now.  However any code that depends on `Enumerator`,
`Builder`, or `Device` implementing `FromRaw` will break with this
change, therefore this probably needs to be published to crates.io with
an incremented version number.

Closes #18

### CODE REVIEW

**Review by Veetaha — APPROVED** [review]

**Comment by anelson** [comment]
@Drakulix could you take a look at this PR when you have a moment?  It seems to be a pretty serious issue at least on older `libudev` versions...

**Comment by Drakulix** [comment]
Yes, I want to and from a first glance the approach looks fine, but I am currently on holiday.
I will try to take care sometime next week.

**Comment by Drakulix** [comment]
First of all, thanks for the PR. I agree, that relying on undefined behavior of libudev was not the best idea.

Removing `FromRaw` without any replacements however will not work, as some use-cases for this exist. E.g. integration with my own libinput-bindings, which can create udev-devices (which are then bound to the libinput-context, which contains the udev-context).

So a proper fix would probably make all of them generic over clonable contexts, which would make the api a lot worse.
Older versions of udev-rs contained a [`FromRawWithContext` trait](https://github.com/Smithay/udev-rs/pull/2/files#diff-555480f27ea06ad30fcc1321c38acf55L34). This is probably the best solution.
But if you have any better ideas, let me know.

**Comment by anelson** [comment]
I think I understand.  The reason I had to remove `FromRaw` is because with this refactoring having a raw `libudev` pointer type isn't enough to instantiate the corresponding wrapper type; one also needs a `Udev` instance which I made private to the crate to keep the surface area of the change minimal.

What if I add a `udev` parameter to `from_raw`?  Then the `FromRaw` would look something like:

```rust
pub trait FromRaw<T: 'static> {
     unsafe fn from_raw(udev: *mut ffi::udev, ptr: *mut T) -> Self;
}
```

Thoughts?

**Comment by Drakulix** [comment]
Yes, that would work, but it would also be weird, that you could create these objects from a context pointer, but not get the context pointer of already created udev objects.

I would additionally either add a `context`-function to `AsRaw`, something like this:
```
pub trait AsRaw<...> {
    // ... as_raw ...
   fn context(&self) -> *mut ffi::udev;
}
```

**Or** just make `Udev` public and accessible. This is changing the API anyway, adding the `Udev`-struct to the public api is not really harmful.

Like this we could also allow creation of a context manually and add constructors like `from_syspath_with_context`. This would not break the old api any further, but additionally allow finer control over the used context.

**Comment by anelson** [comment]
Ok I've taken another crack at it.  Now `Udev` is part of the public API, and `FromRawWithContext` and `AsRawWithContext` are new traits which provide the same functionality as `FromRaw/AsRaw` but with a `udev` pointer.

**Comment by Drakulix** [comment]
Looks good. I will merge and release this in the next couple of days.

**Comment by hodgesds** [comment]
Any ETA on when this will get merged? I'm interested in potentially using this library.

**Comment by Drakulix** [comment]
done :)

**Pull request merged**
