### PR TITLE
chore: bump version to 0.9.1

### PR DESCRIPTION
**Pull request by tiagolobocastro**
With change `feat(monitor/kernel): allow monitoring kernel events`

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
@Drakulix would it be possible to release 0.9.1? Thank you

**Review by Drakulix — APPROVED** [review]
Sorry for getting back at this so late, appreciate the ping!
LGTM

**Comment by Drakulix** [comment]
Published https://github.com/Smithay/udev-rs/actions/runs/11459505046/job/31884206818

**Comment by tiagolobocastro** [comment]
> Sorry for getting back at this so late, appreciate the ping! LGTM

No at all, thank you!

**Pull request merged**
