### PR TITLE
Remove context

### PR DESCRIPTION
**Pull request by Ravenslofty**
This is a port of dcuddeback/libudev-rs#22 by @agrover, removing `udev::Context` from the API. This cleans up a fair bit of code, and I took the opportunity to perform internal cleanup too, which should make it more maintainable.

### CODE REVIEW

**Comment by gilligan** [comment]
Cool, i was actually just looking around for a udev library for Rust - any feedback from the library authors on this one? :)

**Comment by Drakulix** [comment]
First of all: Thanks for you work.

I will try to give this a proper review in the following days, but what I gathered from a first read:

- I did not know, the context was entirely optional. I support this change and think it greatly simplifies the API.

- I would wish you could split the commit into some smaller chunks:
    - Removal of context
    - Adjusting examples
    - Refactoring (also split into different refactoring commits, if unrelated to each other)

You may wanna wait on my full review though, as the current state of this PR might be good enough the way it is, if I do not find any other points worth discussing.

Thanks!

**Comment by Ravenslofty** [comment]
Indeed, as both the systemd libudev and eudev libudev source show, there's no actual state inside of a `struct udev`.

https://github.com/systemd/systemd/blob/master/src/libudev/libudev.c#L25
https://github.com/gentoo/eudev/blob/master/src/libudev/libudev.c#L47

> I would wish you could split the commit into some smaller chunks:
> - Removal of context
> - Adjusting examples

Personally I feel these belong in the same commit, because if a bug needs to be bisected, and the examples don't build because the API changed it wouldn't be very helpful. But I would be happy to move the refactoring out to separate commits.

**Comment by Drakulix** [comment]
That is a very valid point. Then please move out the refactoring.

**Comment by Ravenslofty** [comment]
It's been so long since I've touched this code that I forgot I already *had*. 🤦‍♂ 

The straight port is 2e00c49, while the refactorings are a82f5d2.

**Comment by Drakulix** [comment]
Alright, looks fine to me!

Just some notes, in case you plan to do any further work:
1. You have some reformatting in the first commit. I do welcome those changes, but I would like this split of, where possible.
2. You also have one or two doc fixes, again same deal.
3. I like to increase the create version in a separate commit.

But overall, this is fine for the proposed changes and I am going to release 0.3 after this merge anyway.

**Comment by Ravenslofty** [comment]
Thank you very much!

**Pull request merged**
